### ISSUE TITLE
Can't backup site

### ISSUE THREAD

**Issue by TheTechRobo** [ArchiveTeam/grab-site#181]
I am trying to back up a site.

Here is what I run and the output.

```
$ grab-site --concurrency 1 --delay 1000 https://www.khanacademy.org/test-prep/mcat | elivepaste
psutil: No module named 'psutil'. Resource monitoring will be unavailable.
Manhole[15652:1620244873.7482]: Patched <built-in function fork> and <built-in function forkpty>.
Manhole[15652:1620244873.7793]: Manhole UDS path: /tmp/manhole-15652
Manhole[15652:1620244873.7794]: Waiting for new connection (in pid:15652) ...
/home/thetechrobo/gs-venv/lib/python3.7/site-packages/sqlalchemy/sql/coercions.py:308: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
  "implicitly coercing SELECT object to scalar subquery; "
/home/thetechrobo/gs-venv/lib/python3.7/site-packages/wpull/protocol/http/client.py:185: UserWarning: HTTP session did not complete.
  warnings.warn(_('HTTP session did not complete.'))
ERROR Fatal exception.
Traceback (most recent call last):
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1936, in _do_pre_synchronize_evaluate
    eval_condition = evaluator_compiler.process(*crit)
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/sqlalchemy/orm/evaluator.py", line 85, in process
    return meth(clause)
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/sqlalchemy/orm/evaluator.py", line 181, in visit_binary
    map(self.process, [clause.left, clause.right])
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/sqlalchemy/orm/evaluator.py", line 85, in process
    return meth(clause)
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/sqlalchemy/orm/evaluator.py", line 88, in visit_grouping
    return self.process(clause.element)
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/sqlalchemy/orm/evaluator.py", line 83, in process
    "Cannot evaluate %s" % type(clause).__name__
sqlalchemy.orm.evaluator.UnevaluatableError: Cannot evaluate Select

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/wpull/application/app.py", line 157, in run
    yield from pipeline.process()
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/wpull/pipeline/pipeline.py", line 194, in process
    yield from self._process_one_worker()
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/wpull/pipeline/pipeline.py", line 215, in _process_one_worker
    task.result()
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/wpull/pipeline/pipeline.py", line 119, in process
    item = yield from self.process_one(_worker_id=worker_id)
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/wpull/pipeline/pipeline.py", line 103, in process_one
    yield from task.process(item)
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/wpull/application/tasks/download.py", line 421, in process
    yield from session.app_session.factory['Processor'].process(session)
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/wpull/processor/delegate.py", line 29, in process
    return (yield from processor.process(item_session))
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/wpull/processor/web.py", line 91, in process
    return (yield from session.process())
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/wpull/processor/web.py", line 185, in process
    yield from self._process_loop()
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/wpull/processor/web.py", line 244, in _process_loop
    exit_early, wait_time = yield from self._fetch_one(cast(Request, self._item_session.request))
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/wpull/processor/web.py", line 308, in _fetch_one
    action = self._handle_response(request, response)
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/wpull/processor/web.py", line 410, in _handle_response
    self._item_session.update_record_value(status_code=response.status_code)
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/wpull/pipeline/session.py", line 176, in update_record_value
    self.app_session.factory['URLTable'].update_one(self.url_record.url, **kwargs)
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/wpull/database/wrap.py", line 72, in update_one
    return self.url_table.update_one(*args, **kwargs)
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/wpull/database/sqltable.py", line 196, in update_one
    session.execute(query)
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1638, in execute
    _parent_execute_state is not None,
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1821, in orm_pre_session_exec
    update_options,
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1949, in _do_pre_synchronize_evaluate
    from_=err,
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
sqlalchemy.exc.InvalidRequestError: Could not evaluate current criteria in Python: "Cannot evaluate Select". Specify 'fetch' or False for the synchronize_session execution option.
CRITICAL Sorry, Wpull unexpectedly crashed.
```

Sorry if this is a stupid question, i'm a newcomer.

**Comment by ivan** [comment]
Thank you for the report, I believe this is caused by a sqlalchemy 1.4 incompatibility as found in https://github.com/ArchiveTeam/wpull/issues/463.

I will try to get this fixed soon. In the meantime, the Nix-based grab-site install might work (it still has the older sqlalchemy): https://github.com/ArchiveTeam/grab-site#install-on-another-distribution-lacking-python-37x

**Comment by TheTechRobo** [comment]
Running `pip3 uninstall sqlalchemy` followed by `pip3 install sqlalchemy==1.3.\*` works for me. I'm still puzzled over the `Disconnected from ws:// server: ConnectionRefusedError(111, "Connect call failed ('127.0.0.1', 29000)")`, is this a separate issue?

**Comment by TheTechRobo** [comment]
Figured it out. `gs-server` wasn't running.

**Comment by ivan** [comment]
This should be fixed in grab-site 2.2.1.
