### ISSUE TITLE
Syntax Error on run

### ISSUE THREAD

**Issue by RiversideRocks** [ArchiveTeam/grab-site#214]
```
# ./grab-site --input-file=hfd.txt
Traceback (most recent call last):
  File "/root/grab-site/./grab-site", line 4, in <module>
    main.main()
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/root/grab-site/libgrabsite/main.py", line 371, in main
    from wpull.processor.web import WebProcessor
  File "/usr/local/lib/python3.9/dist-packages/wpull/processor/web.py", line 18, in <module>
    from wpull.processor.coprocessor.phantomjs import PhantomJSCoprocessor
  File "/usr/local/lib/python3.9/dist-packages/wpull/processor/coprocessor/phantomjs.py", line 19, in <module>
    from wpull.driver.phantomjs import PhantomJSDriverParams, PhantomJSDriver
  File "/usr/local/lib/python3.9/dist-packages/wpull/driver/phantomjs.py", line 10, in <module>
    from wpull.driver.process import Process
  File "/usr/local/lib/python3.9/dist-packages/wpull/driver/process.py", line 56
    self._stderr_reader = asyncio.async(self._read_stderr())
                                  ^
SyntaxError: invalid syntax
```

**Comment by ivan** [comment]
grab-site works only when installed as per the instructions in the README, and does not support Python 3.9 yet (Python 3 has broken backwards compat a lot.)
